#!/usr/local/bin/perl -w 

use strict;

use lib "../cgi-modules";

use GKB::WebUtils;
use GKB::Config;

eval {
    my $wu = GKB::WebUtils->new_from_cgi();

    my @tmp = $wu->cgi->param('ID');
    my @ids;
    foreach (@tmp) {
	if (/^(\d+)$/) {
	    push @ids, $1;
	}
    }
    @ids = sort {$a <=> $b}  @ids;
	
    my $id = [$ids[0]];
    my $basename = join('_', $PROJECT_NAME, @$id);
 
    my $tarball = "/cgi-tmp/protege/$basename.tar.gz";

    unless (-e "$GK_TMP_IMG_DIR/protege/$basename.tar.gz"){
       $wu->create_protege_project_wo_orthologues($basename,$id);
    }
    
    print $wu->cgi->redirect($tarball);
};
if ($@) {
    print <<__HERE__;
Contentype: text/plain; charset=ISO-8859-1

$@
__HERE__
}
